name = "fleet-edge"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
account_id = "049ff5e84ecf636b53b162cbb580aae6"

[vars]
VERSION = "0.1.0"
FLEET_NAME = "superinstance"

[[kv_namespaces]]
binding = "FLEET_KV"
id = "3db4cb084224415cada2c97d84365491"
